from rest_framework.views import exception_handler

def custom_api_exception_handler(exc, context):
    # Call REST framework's default exception handler first
    response = exception_handler(exc, context)

    # If a response is generated by DRF (400, 401, 403, 404, etc.)
    if response is not None:
        # Extract the original error details
        original_detail = response.data
        
        # Build our standardized response payload
        custom_response_data = {
            "success": False,
            "error_type": exc.__class__.__name__,
            "status_code": response.status_code,
            # If the error is a dictionary (like form validation), keep it. 
            # Otherwise, wrap the string detail in a predictable key.
            "message": original_detail if isinstance(original_detail, dict) else {"detail": original_detail},
            "path": context['request'].path
        }
        
        # Overwrite the original response data
        response.data = custom_response_data

    return response